### ISSUE TITLE
`actionsDict` is not bound to `this`

### ISSUE THREAD

**Issue by epeli** [wkrueger/redutser#2]
Ie. cannot call another action via `this`.

Example: 

```js
	const initialState = { s: "" }
    const red = createRedutser(initialState, {
      a(state, act: {}) {
        return this.b(state, act)
      },

      b(state, act: {}) {
        return {
          s: state.s + "b",
        }
      },
    })
```

This gives weird type errors

![image](https://user-images.githubusercontent.com/225712/40477082-3df412ec-5f4e-11e8-9ed4-f7931d6ca883.png)

and also errors in runtime because `this` is undefined.

I managed to workaround this with following helper:

```typescript
import {mapValues} from "lodash";

type IState = typeof initialState

type ActionCreators = {
    [key: string]: (state: IState, action: any) => IState;
};

export function bindThis<T extends ActionCreators>(obj: T): T {
    const mapped = mapValues(obj, value => {
        if (typeof value === "function") {
            return value.bind(obj);
        }

        return value;
    });

    return (mapped as any) as T;
}

// Usage

const redutser = createRedutser(
    initialState,
    bindThis({ /* actions */ })
);

```

**Comment by wkrueger** [comment]
Having a look at it. (Somehow this project got unwatched on my github so i never saw your issues).

**Comment by wkrueger** [comment]
While the binding issue should be fixed, I couldnt find a decent fix for the inference issues without changing `createRedutser` signature. For now, you can use `createRedutser2` when using `this` in the Dict. Ugly and sad... :(

**Comment by epeli** [comment]
I Might have found a solution for the inference issue. Here's a patch for it

https://github.com/epeli/redutser/commit/a34d87ed4bae50491112e3728ce77ee276bfc5c2

This builds on the PR #4. 

The idea is to explicitly add typing for `this`

![image](https://user-images.githubusercontent.com/225712/40831452-b405953e-6591-11e8-96fe-fdc4edf0632c.png)

I did not sent PR for this because this [breaks the subdomain specs][1] and currently I don't have time to look at it.

[1]: https://gist.github.com/epeli/7129b2a66948a88a56380c072de672ff

**Comment by wkrueger** [comment]
I probably have tried something similar and ended up in a loophole where one of the inferred types got to `{}` (which actually means: I couldnt infer but hey I wont throw you an error).

I'll have a look on your gist, thanks!

In the worst case, ts3.0 is promising [partial inference](https://github.com/Microsoft/TypeScript/pull/23696) which may fix things that require this curry workaround.

**Comment by epeli** [comment]
> I probably have tried something similar and ended up in a loophole where one of the inferred types got to {} (which actually means: I couldnt infer but hey I wont throw you an error).

Do you see this with TS 2.9? Seems to be working for me just fine.

**Comment by wkrueger** [comment]
Seems it only happens when you _return_ something from `this`.
"bindToSelf" test (modified) continues to fail on ts 2.9.

About your suggestion, that erases the `this` parameter to a generic object instead of receiving the actual object through generics.

I have also tried adding a generic `Self` parameter to `this` too (or even adding a 3rd parameter), but that ends up propagating to the whole codebase and still bringing other new issues (ex: circular references).

So, ugly as it seems, `createRedutser2` still is currently more elegant than the other solutions. I could bring a fancier name for it like `createRedutserCurried`, but well, that is also not much better...

**Comment by esamattis** [comment]
Yeah, I misunderstood the typing situation. `this` is actually an any type but vscode was still clever enought to autocomplete it seemingly right so I misunderstood it.

But I played with style of API from scratch and found out that it can be implemented using classes. So I ended up creating [Immer Reducer](https://github.com/epeli/immer-reducer) based on it.

**Comment by wkrueger** [comment]
Offtopic: I have put redux on soak for the moment. One big issue was the struggle to bring type inference to stateful (classy) connected components.
